// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/test_service.proto

#include "protocol/test_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
#include "log.h"
#include "debug_hub.h"
#include "error_code.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace tpn {
namespace protocol {
constexpr SearchRequest::SearchRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : query_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , page_number_(0)
  , result_per_page_(0){}
struct SearchRequestDefaultTypeInternal {
  constexpr SearchRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SearchRequestDefaultTypeInternal() {}
  union {
    SearchRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SearchRequestDefaultTypeInternal _SearchRequest_default_instance_;
constexpr SearchResponse::SearchResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : results_(){}
struct SearchResponseDefaultTypeInternal {
  constexpr SearchResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SearchResponseDefaultTypeInternal() {}
  union {
    SearchResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SearchResponseDefaultTypeInternal _SearchResponse_default_instance_;
constexpr Result::Result(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : snippets_()
  , url_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , title_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct ResultDefaultTypeInternal {
  constexpr ResultDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ResultDefaultTypeInternal() {}
  union {
    Result _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ResultDefaultTypeInternal _Result_default_instance_;
}  // namespace protocol
}  // namespace tpn
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_protocol_2ftest_5fservice_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_protocol_2ftest_5fservice_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* file_level_service_descriptors_protocol_2ftest_5fservice_2eproto[3];

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_protocol_2ftest_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::SearchRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::SearchRequest, query_),
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::SearchRequest, page_number_),
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::SearchRequest, result_per_page_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::SearchResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::SearchResponse, results_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::Result, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::Result, url_),
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::Result, title_),
  PROTOBUF_FIELD_OFFSET(::tpn::protocol::Result, snippets_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tpn::protocol::SearchRequest)},
  { 8, -1, sizeof(::tpn::protocol::SearchResponse)},
  { 14, -1, sizeof(::tpn::protocol::Result)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tpn::protocol::_SearchRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tpn::protocol::_SearchResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tpn::protocol::_Result_default_instance_),
};

const char descriptor_table_protodef_protocol_2ftest_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033protocol/test_service.proto\022\014tpn.proto"
  "col\032\023type/rpc_type.proto\"L\n\rSearchReques"
  "t\022\r\n\005query\030\001 \001(\t\022\023\n\013page_number\030\002 \001(\005\022\027\n"
  "\017result_per_page\030\003 \001(\005\"7\n\016SearchResponse"
  "\022%\n\007results\030\001 \003(\0132\024.tpn.protocol.Result\""
  "6\n\006Result\022\013\n\003url\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\020\n"
  "\010snippets\030\003 \003(\t2\347\001\n\014TestService1\022W\n\026Proc"
  "essClientRequest11\022\033.tpn.protocol.Search"
  "Request\032\030.tpn.protocol.NoResponse\"\006\202\371+\002\010"
  "\001\022[\n\026ProcessClientRequest12\022\033.tpn.protoc"
  "ol.SearchRequest\032\034.tpn.protocol.SearchRe"
  "sponse\"\006\202\371+\002\010\002\032!\202\371+\035\n\031tpn.protocol.tests"
  "ervice1\020\0012\350\001\n\014TestService2\022W\n\026ProcessCli"
  "entRequest21\022\033.tpn.protocol.SearchReques"
  "t\032\030.tpn.protocol.NoResponse\"\006\202\371+\002\010\001\022[\n\026P"
  "rocessClientRequest22\022\033.tpn.protocol.Sea"
  "rchRequest\032\034.tpn.protocol.SearchResponse"
  "\"\006\202\371+\002\010\002\032\"\202\371+\036\n\032tpn.protocol.testservice"
  "s2\030\0012\352\001\n\014TestService3\022W\n\026ProcessClientRe"
  "quest31\022\033.tpn.protocol.SearchRequest\032\030.t"
  "pn.protocol.NoResponse\"\006\202\371+\002\010\001\022[\n\026Proces"
  "sClientRequest32\022\033.tpn.protocol.SearchRe"
  "quest\032\034.tpn.protocol.SearchResponse\"\006\202\371+"
  "\002\010\002\032$\202\371+ \n\032tpn.protocol.testservices3\020\001\030"
  "\001B\005H\001\200\001\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_protocol_2ftest_5fservice_2eproto_deps[1] = {
  &::descriptor_table_type_2frpc_5ftype_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_protocol_2ftest_5fservice_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protocol_2ftest_5fservice_2eproto = {
  false, false, 976, descriptor_table_protodef_protocol_2ftest_5fservice_2eproto, "protocol/test_service.proto", 
  &descriptor_table_protocol_2ftest_5fservice_2eproto_once, descriptor_table_protocol_2ftest_5fservice_2eproto_deps, 1, 3,
  schemas, file_default_instances, TableStruct_protocol_2ftest_5fservice_2eproto::offsets,
  file_level_metadata_protocol_2ftest_5fservice_2eproto, file_level_enum_descriptors_protocol_2ftest_5fservice_2eproto, file_level_service_descriptors_protocol_2ftest_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_protocol_2ftest_5fservice_2eproto_getter() {
  return &descriptor_table_protocol_2ftest_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_protocol_2ftest_5fservice_2eproto(&descriptor_table_protocol_2ftest_5fservice_2eproto);
namespace tpn {
namespace protocol {

// ===================================================================

class SearchRequest::_Internal {
 public:
};

SearchRequest::SearchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:tpn.protocol.SearchRequest)
}
SearchRequest::SearchRequest(const SearchRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  query_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_query().empty()) {
    query_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_query(), 
      GetArenaForAllocation());
  }
  ::memcpy(&page_number_, &from.page_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&result_per_page_) -
    reinterpret_cast<char*>(&page_number_)) + sizeof(result_per_page_));
  // @@protoc_insertion_point(copy_constructor:tpn.protocol.SearchRequest)
}

inline void SearchRequest::SharedCtor() {
query_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&page_number_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&result_per_page_) -
    reinterpret_cast<char*>(&page_number_)) + sizeof(result_per_page_));
}

SearchRequest::~SearchRequest() {
  // @@protoc_insertion_point(destructor:tpn.protocol.SearchRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SearchRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  query_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SearchRequest::ArenaDtor(void* object) {
  SearchRequest* _this = reinterpret_cast< SearchRequest* >(object);
  (void)_this;
}
void SearchRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SearchRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SearchRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:tpn.protocol.SearchRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  query_.ClearToEmpty();
  ::memset(&page_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&result_per_page_) -
      reinterpret_cast<char*>(&page_number_)) + sizeof(result_per_page_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SearchRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string query = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_query();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tpn.protocol.SearchRequest.query"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 page_number = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          page_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 result_per_page = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          result_per_page_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SearchRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tpn.protocol.SearchRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string query = 1;
  if (!this->_internal_query().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_query().data(), static_cast<int>(this->_internal_query().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tpn.protocol.SearchRequest.query");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_query(), target);
  }

  // int32 page_number = 2;
  if (this->_internal_page_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_page_number(), target);
  }

  // int32 result_per_page = 3;
  if (this->_internal_result_per_page() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_result_per_page(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tpn.protocol.SearchRequest)
  return target;
}

size_t SearchRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tpn.protocol.SearchRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string query = 1;
  if (!this->_internal_query().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_query());
  }

  // int32 page_number = 2;
  if (this->_internal_page_number() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_page_number());
  }

  // int32 result_per_page = 3;
  if (this->_internal_result_per_page() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_result_per_page());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SearchRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SearchRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SearchRequest::GetClassData() const { return &_class_data_; }

void SearchRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<SearchRequest *>(to)->MergeFrom(
      static_cast<const SearchRequest &>(from));
}


void SearchRequest::MergeFrom(const SearchRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tpn.protocol.SearchRequest)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_query().empty()) {
    _internal_set_query(from._internal_query());
  }
  if (from._internal_page_number() != 0) {
    _internal_set_page_number(from._internal_page_number());
  }
  if (from._internal_result_per_page() != 0) {
    _internal_set_result_per_page(from._internal_result_per_page());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SearchRequest::CopyFrom(const SearchRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tpn.protocol.SearchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SearchRequest::IsInitialized() const {
  return true;
}

void SearchRequest::InternalSwap(SearchRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &query_, GetArenaForAllocation(),
      &other->query_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SearchRequest, result_per_page_)
      + sizeof(SearchRequest::result_per_page_)
      - PROTOBUF_FIELD_OFFSET(SearchRequest, page_number_)>(
          reinterpret_cast<char*>(&page_number_),
          reinterpret_cast<char*>(&other->page_number_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SearchRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_protocol_2ftest_5fservice_2eproto_getter, &descriptor_table_protocol_2ftest_5fservice_2eproto_once,
      file_level_metadata_protocol_2ftest_5fservice_2eproto[0]);
}

// ===================================================================

class SearchResponse::_Internal {
 public:
};

SearchResponse::SearchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  results_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:tpn.protocol.SearchResponse)
}
SearchResponse::SearchResponse(const SearchResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      results_(from.results_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tpn.protocol.SearchResponse)
}

inline void SearchResponse::SharedCtor() {
}

SearchResponse::~SearchResponse() {
  // @@protoc_insertion_point(destructor:tpn.protocol.SearchResponse)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SearchResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SearchResponse::ArenaDtor(void* object) {
  SearchResponse* _this = reinterpret_cast< SearchResponse* >(object);
  (void)_this;
}
void SearchResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SearchResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SearchResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:tpn.protocol.SearchResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  results_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SearchResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .tpn.protocol.Result results = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_results(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SearchResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tpn.protocol.SearchResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tpn.protocol.Result results = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_results_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_results(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tpn.protocol.SearchResponse)
  return target;
}

size_t SearchResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tpn.protocol.SearchResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .tpn.protocol.Result results = 1;
  total_size += 1UL * this->_internal_results_size();
  for (const auto& msg : this->results_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SearchResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SearchResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SearchResponse::GetClassData() const { return &_class_data_; }

void SearchResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<SearchResponse *>(to)->MergeFrom(
      static_cast<const SearchResponse &>(from));
}


void SearchResponse::MergeFrom(const SearchResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tpn.protocol.SearchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  results_.MergeFrom(from.results_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SearchResponse::CopyFrom(const SearchResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tpn.protocol.SearchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SearchResponse::IsInitialized() const {
  return true;
}

void SearchResponse::InternalSwap(SearchResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  results_.InternalSwap(&other->results_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SearchResponse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_protocol_2ftest_5fservice_2eproto_getter, &descriptor_table_protocol_2ftest_5fservice_2eproto_once,
      file_level_metadata_protocol_2ftest_5fservice_2eproto[1]);
}

// ===================================================================

class Result::_Internal {
 public:
};

Result::Result(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  snippets_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:tpn.protocol.Result)
}
Result::Result(const Result& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      snippets_(from.snippets_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  url_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_url().empty()) {
    url_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_url(), 
      GetArenaForAllocation());
  }
  title_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_title().empty()) {
    title_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_title(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:tpn.protocol.Result)
}

inline void Result::SharedCtor() {
url_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
title_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

Result::~Result() {
  // @@protoc_insertion_point(destructor:tpn.protocol.Result)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Result::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  url_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  title_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Result::ArenaDtor(void* object) {
  Result* _this = reinterpret_cast< Result* >(object);
  (void)_this;
}
void Result::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Result::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Result::Clear() {
// @@protoc_insertion_point(message_clear_start:tpn.protocol.Result)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  snippets_.Clear();
  url_.ClearToEmpty();
  title_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Result::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string url = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_url();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tpn.protocol.Result.url"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string title = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_title();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tpn.protocol.Result.title"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string snippets = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_snippets();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tpn.protocol.Result.snippets"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Result::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tpn.protocol.Result)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string url = 1;
  if (!this->_internal_url().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_url().data(), static_cast<int>(this->_internal_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tpn.protocol.Result.url");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_url(), target);
  }

  // string title = 2;
  if (!this->_internal_title().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_title().data(), static_cast<int>(this->_internal_title().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tpn.protocol.Result.title");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_title(), target);
  }

  // repeated string snippets = 3;
  for (int i = 0, n = this->_internal_snippets_size(); i < n; i++) {
    const auto& s = this->_internal_snippets(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tpn.protocol.Result.snippets");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tpn.protocol.Result)
  return target;
}

size_t Result::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tpn.protocol.Result)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string snippets = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(snippets_.size());
  for (int i = 0, n = snippets_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      snippets_.Get(i));
  }

  // string url = 1;
  if (!this->_internal_url().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_url());
  }

  // string title = 2;
  if (!this->_internal_title().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_title());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Result::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Result::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Result::GetClassData() const { return &_class_data_; }

void Result::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<Result *>(to)->MergeFrom(
      static_cast<const Result &>(from));
}


void Result::MergeFrom(const Result& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tpn.protocol.Result)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  snippets_.MergeFrom(from.snippets_);
  if (!from._internal_url().empty()) {
    _internal_set_url(from._internal_url());
  }
  if (!from._internal_title().empty()) {
    _internal_set_title(from._internal_title());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Result::CopyFrom(const Result& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tpn.protocol.Result)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Result::IsInitialized() const {
  return true;
}

void Result::InternalSwap(Result* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  snippets_.InternalSwap(&other->snippets_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &url_, GetArenaForAllocation(),
      &other->url_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &title_, GetArenaForAllocation(),
      &other->title_, other->GetArenaForAllocation()
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Result::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_protocol_2ftest_5fservice_2eproto_getter, &descriptor_table_protocol_2ftest_5fservice_2eproto_once,
      file_level_metadata_protocol_2ftest_5fservice_2eproto[2]);
}

// ===================================================================

TestService1::TestService1(bool use_original_hash) : service_hash_(use_original_hash ? OriginalHash::value : NameHash::value) {
}

TestService1::~TestService1() {
}

const google::protobuf::ServiceDescriptor *TestService1::descriptor() {
  google::protobuf::internal::AssignDescriptors(&descriptor_table_protocol_2ftest_5fservice_2eproto);
  return  file_level_service_descriptors_protocol_2ftest_5fservice_2eproto[0];
}

void TestService1::ProcessClientRequest11(const ::tpn::protocol::SearchRequest *request, bool client /*= false*/, bool server /*= false*/) {
  LOG_DEBUG("{} Server called client method TestService1.ProcessClientRequest11(tpn.protocol.SearchRequest{{ {}  }})",
    GetCallerInfo(), request->ShortDebugString());
  SendRequest(service_hash_, 1 | (client ? 0x40000000 : 0) | (server ? 0x80000000 : 0), request);
}

void TestService1::ProcessClientRequest12(const ::tpn::protocol::SearchRequest *request, std::function<void(const ::tpn::protocol::SearchResponse *)> response_callback, bool client /*= false*/, bool server /*= false*/) {
  LOG_DEBUG("{} Server called client method TestService1.ProcessClientRequest12(tpn.protocol.SearchRequest{{ {} }})",
    GetCallerInfo(), request->ShortDebugString());
  std::function<void(ByteBuffer)> callback = [response_callback](ByteBuffer buffer) -> void {
    ::tpn::protocol::SearchResponse response;
    if (response.ParseFromArray(buffer.GetContents(), buffer.GetSize()))
      response_callback(&response);
  };
  SendRequest(service_hash_, 2 | (client ? 0x40000000 : 0) | (server ? 0x80000000 : 0), request, std::move(callback));
}

void TestService1::CallServerMethod(uint32_t token, uint32_t method_id, ByteBuffer /*buffer*/) {
  LOG_ERROR("{} Server tried to call server method {}",
    GetCallerInfo(), method_id);
}

// ===================================================================

TestService2::TestService2(bool use_original_hash) : service_hash_(use_original_hash ? OriginalHash::value : NameHash::value) {
}

TestService2::~TestService2() {
}

const google::protobuf::ServiceDescriptor *TestService2::descriptor() {
  google::protobuf::internal::AssignDescriptors(&descriptor_table_protocol_2ftest_5fservice_2eproto);
  return  file_level_service_descriptors_protocol_2ftest_5fservice_2eproto[1];
}

void TestService2::CallServerMethod(uint32_t token, uint32_t method_id, ByteBuffer buffer) {
  switch(method_id & 0x3FFFFFFF) {
    case 1: {
      ::tpn::protocol::SearchRequest request;
      if (!request.ParseFromArray(buffer.GetContents(), buffer.GetSize())) {
        LOG_DEBUG("{} Failed to parse request for TestService2.ProcessClientRequest21 server method call.", GetCallerInfo());
        SendResponse(service_hash_, method_id, token, kErrorCodeMalformedRequest);
        return;
      }
      uint32_t status = HandleProcessClientRequest21(&request);
      LOG_DEBUG("{} Client called server method TestService2.ProcessClientRequest21(tpn.protocol.SearchRequest{{ {} }}) status {}.",
        GetCallerInfo(), request.ShortDebugString(), status);
      if (status)
        SendResponse(service_hash_, method_id, token, status);
      break;
    }
    case 2: {
      ::tpn::protocol::SearchRequest request;
      if (!request.ParseFromArray(buffer.GetContents(), buffer.GetSize())) {
        LOG_DEBUG("{} Failed to parse request for TestService2.ProcessClientRequest22 server method call.", GetCallerInfo());
        SendResponse(service_hash_, method_id, token, kErrorCodeMalformedRequest);
        return;
      }
      LOG_DEBUG("{} Client called server method TestService2.ProcessClientRequest22(tpn.protocol.SearchRequest{{ {} }}).",
GetCallerInfo(), request.ShortDebugString());
      std::function<void(ServiceBase*, uint32_t, const google::protobuf::Message *)> continuation = [token, method_id](ServiceBase *service, uint32_t status, const google::protobuf::Message *response)
      {
        TPN_ASSERT(response->GetDescriptor() == ::tpn::protocol::SearchResponse::descriptor(), "response descriptor error {} != {}", response->GetDescriptor()->DebugString(), ::tpn::protocol::SearchResponse::descriptor()->DebugString());
        TestService2* self = static_cast<TestService2*>(service);
        LOG_DEBUG("{} Client called server method TestService2.ProcessClientRequest22() returned tpn.protocol.SearchResponse{{ {} }} status {}.",
          self->GetCallerInfo(), response->ShortDebugString(), status);
        if (!status)
          self->SendResponse(self->service_hash_, method_id, token, response);
        else
          self->SendResponse(self->service_hash_, method_id, token, status);
      };
      ::tpn::protocol::SearchResponse response;
      uint32_t status = HandleProcessClientRequest22(&request, &response, continuation);
      if (continuation)
        continuation(this, status, &response);
      break;
    }
    default:
      LOG_ERROR("Bad method id {}.", method_id);
      SendResponse(service_hash_, method_id, token, kErrorCodeInvalidMethod);
      break;
    }
}

uint32_t TestService2::HandleProcessClientRequest21(const ::tpn::protocol::SearchRequest *request) {
  LOG_ERROR("{} Client tried to call not implemented method TestService2.ProcessClientRequest21({{ {} }})",
    GetCallerInfo(), request->ShortDebugString());
  return kErrorCodeNotImplemented;
}

uint32_t TestService2::HandleProcessClientRequest22(const ::tpn::protocol::SearchRequest *request, ::tpn::protocol::SearchResponse *response, std::function<void(ServiceBase*, uint32_t, const google::protobuf::Message *)>& continuation) {
  LOG_ERROR("{} Client tried to call not implemented method TestService2.ProcessClientRequest22({{ {} }})",
    GetCallerInfo(), request->ShortDebugString());
  return kErrorCodeNotImplemented;
}

// ===================================================================

TestService3::TestService3(bool use_original_hash) : service_hash_(use_original_hash ? OriginalHash::value : NameHash::value) {
}

TestService3::~TestService3() {
}

const google::protobuf::ServiceDescriptor *TestService3::descriptor() {
  google::protobuf::internal::AssignDescriptors(&descriptor_table_protocol_2ftest_5fservice_2eproto);
  return  file_level_service_descriptors_protocol_2ftest_5fservice_2eproto[2];
}

void TestService3::ProcessClientRequest31(const ::tpn::protocol::SearchRequest *request, bool client /*= false*/, bool server /*= false*/) {
  LOG_DEBUG("{} Server called client method TestService3.ProcessClientRequest31(tpn.protocol.SearchRequest{{ {}  }})",
    GetCallerInfo(), request->ShortDebugString());
  SendRequest(service_hash_, 1 | (client ? 0x40000000 : 0) | (server ? 0x80000000 : 0), request);
}

void TestService3::ProcessClientRequest32(const ::tpn::protocol::SearchRequest *request, std::function<void(const ::tpn::protocol::SearchResponse *)> response_callback, bool client /*= false*/, bool server /*= false*/) {
  LOG_DEBUG("{} Server called client method TestService3.ProcessClientRequest32(tpn.protocol.SearchRequest{{ {} }})",
    GetCallerInfo(), request->ShortDebugString());
  std::function<void(ByteBuffer)> callback = [response_callback](ByteBuffer buffer) -> void {
    ::tpn::protocol::SearchResponse response;
    if (response.ParseFromArray(buffer.GetContents(), buffer.GetSize()))
      response_callback(&response);
  };
  SendRequest(service_hash_, 2 | (client ? 0x40000000 : 0) | (server ? 0x80000000 : 0), request, std::move(callback));
}

void TestService3::CallServerMethod(uint32_t token, uint32_t method_id, ByteBuffer buffer) {
  switch(method_id & 0x3FFFFFFF) {
    case 1: {
      ::tpn::protocol::SearchRequest request;
      if (!request.ParseFromArray(buffer.GetContents(), buffer.GetSize())) {
        LOG_DEBUG("{} Failed to parse request for TestService3.ProcessClientRequest31 server method call.", GetCallerInfo());
        SendResponse(service_hash_, method_id, token, kErrorCodeMalformedRequest);
        return;
      }
      uint32_t status = HandleProcessClientRequest31(&request);
      LOG_DEBUG("{} Client called server method TestService3.ProcessClientRequest31(tpn.protocol.SearchRequest{{ {} }}) status {}.",
        GetCallerInfo(), request.ShortDebugString(), status);
      if (status)
        SendResponse(service_hash_, method_id, token, status);
      break;
    }
    case 2: {
      ::tpn::protocol::SearchRequest request;
      if (!request.ParseFromArray(buffer.GetContents(), buffer.GetSize())) {
        LOG_DEBUG("{} Failed to parse request for TestService3.ProcessClientRequest32 server method call.", GetCallerInfo());
        SendResponse(service_hash_, method_id, token, kErrorCodeMalformedRequest);
        return;
      }
      LOG_DEBUG("{} Client called server method TestService3.ProcessClientRequest32(tpn.protocol.SearchRequest{{ {} }}).",
GetCallerInfo(), request.ShortDebugString());
      std::function<void(ServiceBase*, uint32_t, const google::protobuf::Message *)> continuation = [token, method_id](ServiceBase *service, uint32_t status, const google::protobuf::Message *response)
      {
        TPN_ASSERT(response->GetDescriptor() == ::tpn::protocol::SearchResponse::descriptor(), "response descriptor error {} != {}", response->GetDescriptor()->DebugString(), ::tpn::protocol::SearchResponse::descriptor()->DebugString());
        TestService3* self = static_cast<TestService3*>(service);
        LOG_DEBUG("{} Client called server method TestService3.ProcessClientRequest32() returned tpn.protocol.SearchResponse{{ {} }} status {}.",
          self->GetCallerInfo(), response->ShortDebugString(), status);
        if (!status)
          self->SendResponse(self->service_hash_, method_id, token, response);
        else
          self->SendResponse(self->service_hash_, method_id, token, status);
      };
      ::tpn::protocol::SearchResponse response;
      uint32_t status = HandleProcessClientRequest32(&request, &response, continuation);
      if (continuation)
        continuation(this, status, &response);
      break;
    }
    default:
      LOG_ERROR("Bad method id {}.", method_id);
      SendResponse(service_hash_, method_id, token, kErrorCodeInvalidMethod);
      break;
    }
}

uint32_t TestService3::HandleProcessClientRequest31(const ::tpn::protocol::SearchRequest *request) {
  LOG_ERROR("{} Client tried to call not implemented method TestService3.ProcessClientRequest31({{ {} }})",
    GetCallerInfo(), request->ShortDebugString());
  return kErrorCodeNotImplemented;
}

uint32_t TestService3::HandleProcessClientRequest32(const ::tpn::protocol::SearchRequest *request, ::tpn::protocol::SearchResponse *response, std::function<void(ServiceBase*, uint32_t, const google::protobuf::Message *)>& continuation) {
  LOG_ERROR("{} Client tried to call not implemented method TestService3.ProcessClientRequest32({{ {} }})",
    GetCallerInfo(), request->ShortDebugString());
  return kErrorCodeNotImplemented;
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace tpn
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tpn::protocol::SearchRequest* Arena::CreateMaybeMessage< ::tpn::protocol::SearchRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tpn::protocol::SearchRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::tpn::protocol::SearchResponse* Arena::CreateMaybeMessage< ::tpn::protocol::SearchResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tpn::protocol::SearchResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::tpn::protocol::Result* Arena::CreateMaybeMessage< ::tpn::protocol::Result >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tpn::protocol::Result >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
